# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-05 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, unique=True, verbose_name='IP\u5730\u5740')),
                ('device_brand', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u54c1\u724c')),
                ('cpu', models.IntegerField(null=True)),
                ('memory', models.IntegerField(null=True)),
                ('disk', models.IntegerField(null=True)),
                ('sn', models.CharField(max_length=40, null=True)),
                ('up_time', models.DateTimeField(auto_now=True)),
                ('os_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('describtion', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u673a\u623f\u540d')),
                ('address', models.CharField(max_length=255, verbose_name='\u673a\u623f\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u7528\u6237\u7ec4\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('group', models.ManyToManyField(to='app01.UserGroup', verbose_name='\u7528\u6237\u7ec4\u540d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Virt_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virt_ip', models.GenericIPAddressField(null=True, verbose_name='\u865a\u62dfIP')),
                ('virsh_name', models.CharField(max_length=64, verbose_name='\u865a\u62df\u673a\u540d')),
                ('su_host_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Device', verbose_name='\u5bbf\u4e3b\u673aIP')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='machine_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Machine_Room', verbose_name='\u673a\u623f\u540d'),
        ),
    ]
