# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='machine_room_Cabinet',
            field=models.CharField(default='F04', max_length=32, verbose_name='\u673a\u67dc'),
            preserve_default=False,
        ),
    ]
