# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171206_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=255)),
            ],
        ),
    ]
