# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_log_cmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_cmd',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 12, 7, 7, 25, 11, 49000, tzinfo=utc), verbose_name='\u6267\u884c\u547d\u4ee4\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
