# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_log_cmd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operate_room',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u673a\u623f\u540d'),
        ),
        migrations.AlterField(
            model_name='virt_ip',
            name='virt_ip',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name='\u865a\u62dfIP'),
        ),
    ]
