# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171207_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
