# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20171208_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operate_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_host', models.GenericIPAddressField(error_messages={'invalid': 'IP\u683c\u5f0f\u9519\u8bef', 'required': 'IP\u5730\u5740\u4e0d\u80fd\u4e3a\u7a7a'}, protocol='ipv4')),
                ('upload_path', models.CharField(max_length=64, unique=True)),
                ('upload_file', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
